import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/header'
import SideBar from '@/components/SideBar/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Karim Ismail - FrontEnd Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <SideBar />
        </body>
    </html>
  )
}
